name: streamlit_poc_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit
      - llama-index-core==0.11.3
      - llama-index-llms-azure-openai==0.2.0
      - llama-index-embeddings-azure-openai==0.2.4
      - llama-index-readers-file
      